## Split keyboards
## https://zmk.dev/docs/config/system#split-keyboards
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# ## Track words per minute
# CONFIG_ZMK_WPM=y

## ZMK Studio
## https://zmk.dev/docs/features/studio
#ZMK Studio: Поддерживается на Bluetooth и стандартных сборках донгла без экрана для быстрой настройки клавиш. 
#Сборка экранов Prospector отключает её для сохранения оперативной памяти. 
#возможно, это касается только  nice!nano-based stacked build.
#Disable ZMK Studio to preserve RAM alongside LVGL/display features.
CONFIG_ZMK_STUDIO=n
## https://zmk.dev/docs/config/studio
CONFIG_ZMK_STUDIO_LOCKING=y
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=y
CONFIG_ZMK_STUDIO_TRANSPORT_BLE_PREF_LATENCY=5

# Blank the display after idle keyboard time. Idle is measured by ZMK activity
# state and is currently set to 30 seconds here for Prospector builds.
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
CONFIG_ZMK_IDLE_TIMEOUT=30000

# Pointing
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
#devpew:
#CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

